baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Microservice Cookbook'
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "terminal"
paginate = 10

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false

  autoCover = true

  showLastUpdated = false

  # updatedDatePrefix = "Updated"

  # oneHeadingSize = true # default

  # readingTime = false # default

  Toc = true # default

  # TocTitle = "Table of Contents" # default

[module]
  # In case you would like to make changes to the theme and keep it locally in you repository,
  # uncomment the line below (and correct the local path if necessary).
  # --
  # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'

[languages]
  [languages.en]
    title = "Microservice Cookbook"
    subtitle = "A cookbook with useful golang technics"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Microservice Cookbook"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"